// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvZV9PjbZpToyg1kE7bhAbrEAYqeU_VNA',
    appId: '1:746294533414:web:86ccba5eaaeb6213d075e7',
    messagingSenderId: '746294533414',
    projectId: 'clipsync-c0382',
    authDomain: 'clipsync-c0382.firebaseapp.com',
    storageBucket: 'clipsync-c0382.firebasestorage.app',
    measurementId: 'G-MW5XEQZ7SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ62l38mfnFFebwOmWycMfLRBeqtDjnzc',
    appId: '1:746294533414:android:8d0c6dff8bb03234d075e7',
    messagingSenderId: '746294533414',
    projectId: 'clipsync-c0382',
    storageBucket: 'clipsync-c0382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9jgr_5MKf1pkKw99qy9DWn7qQrqtWuLk',
    appId: '1:746294533414:ios:8cd46212b0d4583cd075e7',
    messagingSenderId: '746294533414',
    projectId: 'clipsync-c0382',
    storageBucket: 'clipsync-c0382.firebasestorage.app',
    iosBundleId: 'com.example.clipsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9jgr_5MKf1pkKw99qy9DWn7qQrqtWuLk',
    appId: '1:746294533414:ios:8cd46212b0d4583cd075e7',
    messagingSenderId: '746294533414',
    projectId: 'clipsync-c0382',
    storageBucket: 'clipsync-c0382.firebasestorage.app',
    iosBundleId: 'com.example.clipsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvZV9PjbZpToyg1kE7bhAbrEAYqeU_VNA',
    appId: '1:746294533414:web:d6317ff5a64035d6d075e7',
    messagingSenderId: '746294533414',
    projectId: 'clipsync-c0382',
    authDomain: 'clipsync-c0382.firebaseapp.com',
    storageBucket: 'clipsync-c0382.firebasestorage.app',
    measurementId: 'G-08R9RQQ7YN',
  );
}
